Models/Administration/Module.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace mYSelfERPWeb.Models
{
    [Table("Administration_Module")]
    public class Module
    {
        [Key]
        public int Module_id { get; set; }
        public string Module_name { get; set; }
        public string Icon { get; set; }
        public DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    }
}

ViewModels/Administration/ModuleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mYSelfERPWeb.ViewModels
{
    public class ModuleViewModel
    {
        public int Module_id { get; set; }
        public string Module_name { get; set; }
        public string Icon { get; set; }
        public DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool Active { get; set; }
    }
}

Controllers/Administration/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using mYSelfERPWeb.Models;
using mYSelfERPWeb.Services;
using mYSelfERPWeb.ViewModels;

namespace mYSelfERPWeb.Controllers
{
    public class ModuleController : CoreController
    {

        private readonly IModuleService _moduleService;
        private readonly IMapper _mapper;

        public ModuleController(IModuleService moduleService, IMapper mapper)
        {
            _moduleService = moduleService;
            _mapper = mapper;
        }
        public ActionResult Index()
        {
            var modules = _moduleService.GetAllModules();
            return View(modules);
        }

        public ActionResult Create()
        {
            return View(new ModuleViewModel());
        }


        [HttpPost]
        public ActionResult Create(ModuleViewModel vmModel)
        {
            if (!string.IsNullOrEmpty(vmModel.Module_name))
            {
                var model = _mapper.Map<ModuleViewModel, Module>(vmModel);
                model.Active = true;
                AddAuditTrail(model, true);
                _moduleService.AddModule(model);
                _moduleService.SaveModule();
                AddToastMessage("", "Module has been created successfully.", ToastType.Success);
                return RedirectToAction("Index");

            }
            else
            {
                AddToastMessage("", "Please enter module name  to create new module", ToastType.Error);
                return RedirectToAction("Create");
            }
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = _moduleService.GetModuleById(id);
            var vmodel = _mapper.Map<Module, ModuleViewModel>(model);
            return View("Create",vmodel);
        }


        [HttpPost]
        public ActionResult Edit(ModuleViewModel vmModel)
        {
            if (!string.IsNullOrEmpty(vmModel.Module_name))
            {
                var model = _moduleService.GetModuleById(vmModel.Module_id);
                model.Module_name = vmModel.Module_name;
                AddAuditTrail(model, false);
                _moduleService.UpdateModule(model);
                _moduleService.SaveModule();
                AddToastMessage("", "Module has been updated successfully.", ToastType.Success);
                return RedirectToAction("Index");

            }
            else
            {
                AddToastMessage("", "Please enter module name to update module", ToastType.Error);
                return RedirectToAction("Index");
            }

        }

        [HttpGet]
        public ActionResult ChangeModuleStatus(int id, string status)
        {
            var module = _moduleService.GetModuleById(id);
            module.Active = Convert.ToBoolean(status);
            AddAuditTrail(module, false);
            _moduleService.UpdateModule(module);
            _moduleService.SaveModule();
            AddToastMessage("", "Module status updated successfully.", ToastType.Success);
            return RedirectToAction("Index");
        }
    }
}

Views/Module/Create.cshtml
@using mYSelfERPWeb.Models
@model mYSelfERPWeb.ViewModels.ModuleViewModel
@{
    string actionName = ViewContext.RouteData.Values["action"].ToString();
    Layout = "~/Views/Shared/_Layout.cshtml";


}

<div class="card">

    @using (Html.BeginForm(actionName, "Module", FormMethod.Post, new { id = "demo_form2", enctype = "multipart/form-data", @class = "form-horizontal form-label-left" }))
    {
        @Html.HiddenFor(model => model.Module_id)
        <div class="card card-default">
            <div class="border-bottom title-part-padding">
                <h4 class="card-title mb-0">Create New Module</h4>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Module name</label>
                            @Html.TextBoxFor(model => model.Module_name, new { @class = "form-control", placeholder = "Enter module name" })
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>ICON</label>
                            @Html.TextBoxFor(model => model.Icon, new { @class = "form-control" })
                            <a href="https://fontawesome.com/v4.7.0/icons/" title="Find Icon here" target="_blank"><span class="fa fa-search"></span> Find Icon here and Copy and Paste 'fa fa' icon field.</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-actions">
                <div class="text-end">
                    <button type="submit" class="btn waves-effect waves-light btn-primary">
                        <i class="fa fa-save" aria-hidden="true"></i>Save Module</button>

                </div>
            </div>
        </div>

    }
</div>

Views/Module/Index.cshtml
@model IEnumerable<mYSelfERPWeb.Models.Module>
@{
    ViewBag.Title = "Module List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">

    <div class="d-flex justify-content-between align-items-center">
        <h4 class="card-title">Module List</h4>
        <a href="@Url.Action("Create", "Module")" class="btn waves-effect waves-light btn-primary">
            <i class="fa fa-plus-square" aria-hidden="true" class="fill-white me-2"></i>Add New Module
        </a>
    </div>

    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Module Name</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int sl = 1;
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@(sl++)</td>
                        <td>@item.Module_name</td>
                        <td>
                            @if (item.Active)
                            {
                                <span class="badge bg-success">Active</span>
                            }
                            else
                            {
                                <span class="badge bg-danger">Inactive</span>
                            }
                        </td>
                        <td>
                            <a href="@Url.Action("Edit", "Module", new { id = item.Module_id })">
                                <i class="far fa-edit"></i>
                            </a>
                            @if (item.Active)
                            {
                                <a href="@Url.Action("ChangeModuleStatus", "Module", new { id = item.Module_id, status = "false" })">
                                    <span class="badge bg-danger">Inactive</span>
                                </a>
                            }
                            else
                            {
                                <a href="@Url.Action("ChangeModuleStatus", "Module", new { id = item.Module_id, status = "true" })">
                                    <span class="badge bg-success">Active</span>
                                </a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>