Models/PayRoll/SalaryDeductionElement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace mYSelfERPWeb.Models
{
    [Table("Payroll_Salary_deduction_element")]
    public class SalaryDeductionElement
    {
        [Key]
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
        public string CompanyCode { get; set; }
        public string SisterConcernCode { get; set; }
        public bool? Active { get; set; }
        public byte? IsHave { get; set; }
        public string UserGroupCode { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
    }
}

ViewModels/PayRoll/SalaryDeductionElementViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mYSelfERPWeb.ViewModels
{
    public class SalaryDeductionElementViewModel
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Remarks { get; set; }
        public string CompanyCode { get; set; }
        public string SisterConcernCode { get; set; }
        public bool? Active { get; set; }
        public byte? IsHave { get; set; }
        public string UserGroupCode { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModificationDate { get; set; }
    }
}

Controllers/PayRoll/SalaryDeductionElementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using mYSelfERPWeb.Models;
using mYSelfERPWeb.Services;
using mYSelfERPWeb.ViewModels;

namespace mYSelfERPWeb.Controllers
{
    public class SalaryDeductionElementController : CoreController
    {
        private readonly ISalaryDeductionElementService _salaryDeductionElementService;
        private readonly IMapper _mapper;
        private readonly IMiscellaneousService<SalaryDeductionElement> _miscellaneousService;

        public SalaryDeductionElementController(ISalaryDeductionElementService salaryDeductionElementService, IMapper mapper, IMiscellaneousService<SalaryDeductionElement> miscellaneousService)
        {
            _salaryDeductionElementService = salaryDeductionElementService;
            _mapper = mapper;
            _miscellaneousService = miscellaneousService;
        }
        public ActionResult Index()
        {
            var model = _salaryDeductionElementService.GetAllsalaryDeductionElements();
            return View(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            var code = _miscellaneousService.GetUniqueKey(i => int.Parse(i.Code));
            var model = new SalaryDeductionElementViewModel { Code = code };
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(SalaryDeductionElementViewModel vmModel)
        {
            if (!string.IsNullOrEmpty(vmModel.Name))
            {
                var existingSalaryGroup = _miscellaneousService.GetDuplicateEntry(i => i.Name == vmModel.Name);
                if (existingSalaryGroup != null)
                {
                    AddToastMessage("", "A Salary deduction element with same name already exists in the system. Please try with a different name.", ToastType.Error);
                    return View(vmModel);
                }

                var model = _mapper.Map<SalaryDeductionElementViewModel, SalaryDeductionElement>(vmModel);
                model.CompanyCode = Sessions.Name.CompanyCode;
                model.SisterConcernCode = Sessions.Name.SisterConcernCode;
                model.Active = true;
                AddAuditTrail(model, true);
                _salaryDeductionElementService.AddSalaryDeductionElement(model);
                _salaryDeductionElementService.SaveSalaryDeductionElement();
                AddToastMessage("", "Salary Deduction Element Added successfully", ToastType.Success);
                return RedirectToAction("Index");
            }
            AddToastMessage("", "No data found to save salary deduction element", ToastType.Error);
            return View();
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = _salaryDeductionElementService.GetSalaryDeductionElementById(id);
            var vmodel = _mapper.Map<SalaryDeductionElement, SalaryDeductionElementViewModel>(model);
            return View("Create", vmodel);
        }


        [HttpPost]
        public ActionResult Edit(SalaryDeductionElementViewModel vmModel)
        {
            if (!string.IsNullOrEmpty(vmModel.Name))
            {
                var model = _salaryDeductionElementService.GetSalaryDeductionElementById(vmModel.Id);
                model.Name = vmModel.Name;
                model.Remarks = vmModel.Remarks;
                model.CompanyCode = Sessions.Name.CompanyCode;
                model.SisterConcernCode = Sessions.Name.SisterConcernCode;
                AddAuditTrail(model, false);
                _salaryDeductionElementService.UpdateSalaryDeductionElement(model);
                _salaryDeductionElementService.SaveSalaryDeductionElement();
                AddToastMessage("", "Salary Deduction Element updated successfully", ToastType.Success);
                return RedirectToAction("Index");
            }
            AddToastMessage("", "No data found to update Salary deduction Element", ToastType.Error);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ChangeStatus(int id, string status)
        {
            var salaryDeducctionelement = _salaryDeductionElementService.GetSalaryDeductionElementById(id);
            salaryDeducctionelement.Active = Convert.ToBoolean(status);
            AddAuditTrail(salaryDeducctionelement, false);
            _salaryDeductionElementService.UpdateSalaryDeductionElement(salaryDeducctionelement);
            _salaryDeductionElementService.SaveSalaryDeductionElement();
            AddToastMessage("", "Salary Deduction Element status updated successfully.", ToastType.Success);
            return RedirectToAction("Index");
        }
    }
}

Views/SalaryDeductionElement/Create.cshtml
@using mYSelfERPWeb.Models
@model mYSelfERPWeb.ViewModels.SalaryDeductionElementViewModel
@{
    string actionName = ViewContext.RouteData.Values["action"].ToString();
    Layout = "~/Views/Shared/_Layout.cshtml";

    string headerTitle;
    if (actionName == "Edit")
    {
        headerTitle = "Edit Salary Deduction Element";
    }
    else
    {
        headerTitle = "New Salary Deduction Element ";

    }
}

<div class="card">

    @using (Html.BeginForm(actionName, "SalaryDeductionElement", FormMethod.Post, new { id = "demo_form2", enctype = "multipart/form-data", @class = "form-horizontal form-label-left" }))
    {
        <div class="form-group">
            @Html.HiddenFor(model => model.Id)
        </div>
        <div class="card card-default">
            <div class="border-bottom title-part-padding">
                <h4 class="card-title mb-0">@headerTitle Information</h4>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label>Code</label>
                            @Html.TextBoxFor(model => model.Code, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                    </div>

                    <div class="col-md-9">
                        <div class="form-group">
                            <label>Salary Deduction Element</label>
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control", placeholder = "Enter salary deduction element name" })
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="form-group">
                                <label>Remarks</label>
                                @Html.TextBoxFor(model => model.Remarks, new { @class = "form-control", placeholder = "Enter remarks" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-actions">
                <div class="text-end">
                    <button type="submit" class="btn waves-effect waves-light btn-primary">
                        <i class="fa fa-save" aria-hidden="true"></i>Save Salary Deduction Element
                    </button>
                </div>
            </div>
        </div>

    }
</div>

Views/SalaryDeductionElement/Index.cshtml
@model IEnumerable<mYSelfERPWeb.Models.SalaryDeductionElement>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card">
    <div class="d-flex justify-content-between align-items-center">
        <strong class="card-title">Existing Salary Deduction Element</strong>
        <a href="@Url.Action("Create", "SalaryDeductionElement")" class="btn waves-effect waves-light btn-primary">
            <i class="fa fa-plus-square" aria-hidden="true" class="fill-white me-2"></i> Add New Salary Deduction Element
        </a>
    </div>
</div>
<!-- /.card-header -->
<div class="card-body">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 10px">#</th>
                <th>Code</th>
                <th>Salary Deduction Element</th>
                <th>Remarks</th>
                <th>Status</th>
                <th>Action</th>


            </tr>
        </thead>
        <tbody>
            @{
                int sl = 1;
            }
            @foreach (var item in Model)
            {
                <tr>
                    <td>@(sl++)</td>
                    <td>@item.Code</td>
                    <td>@item.Name</td>
                    <td>@item.Remarks</td>
                    <td>
                        @if (@item.Active == true)
                        {
                            <span class="badge bg-success">Active</span>
                        }
                        else
                        {
                            <span class="badge bg-danger">Inactive</span>
                        }
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "SalaryDeductionElement", new { id = item.Id})">
                            <i class="far fa-edit"></i>
                        </a>
                        @if (@item.Active == true)
                        {
                            <a href="@Url.Action("ChangeStatus", "SalaryDeductionElement", new { id = item.Id, status = "false" })">
                                <span class="badge bg-danger">Inactive</span>
                            </a>
                        }
                        else
                        {
                            <a href="@Url.Action("ChangeStatus", "SalaryDeductionElement", new { id = item.Id, status = "true" })">
                                <span class="badge bg-success">Active</span>
                            </a>
                        }
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>